### ISSUE TITLE
The output of make Clonelib should be clearer

### ISSUE THREAD

**Issue by pjvandehaar** [statgen/bamUtil#19]
When I run 

```
git clone git@github.com:statgen/bamUtil.git
make cloneLib
```

I see:

```
Makefile.inc:17: ../libStatGen/Makefiles/Makefile.tool: No such file or directory
Unable to locate: ./../libStatGen/Makefiles/Makefile.tool
To change the location, set LIB_PATH_GENERAL or LIB_PATH_BAM_UTIL to the appropriate path to libStatGen. Or specify "make LIB_PATH_GENERAL=yourPath" or "make LIB_PATH_BAM_UTIL=yourPath"
Use make cloneLib if you have git and want to clone the current libStatGen at that location.
Cloning into '../libStatGen'...
remote: Counting objects: 4393, done.
remote: Total 4393 (delta 0), reused 0 (delta 0), pack-reused 4393
Receiving objects: 100% (4393/4393), 4.64 MiB | 0 bytes/s, done.
Resolving deltas: 100% (2165/2165), done.
Checking connectivity... done.
Call make to compile libStatGen and this tool.
```

That looks a lot like an error, and it shouldn't.

**Comment by mktrost** [comment]
Fixed with c37893a316cb56ec78fcbff006ce25a54a6e37ec

**Comment by pjvandehaar** [comment]
Thanks Mary Kate!

**Comment by JVidal-Dupiol** [comment]
Dear all,
I'm facing somewhat the same problem but I'm sorry I don't understand what was the solution in your reply mktrost.
ubuntu@ubuntu:/usr/bin/bamUtil$ make clonedLib
Unable to locate: ./../libStatGen/Makefiles/Makefile.tool
To change the location, set LIB_PATH_GENERAL or LIB_PATH_BAM_UTIL to the appropriate path to libStatGen. Or specify "make LIB_PATH_GENERAL=yourPath" or "make LIB_PATH_BAM_UTIL=yourPath"
Use make cloneLib if you have git and want to clone the current libStatGen at that location.
make: *** No rule to make target 'clonedLib'.  Stop.

Best
Jeremie
