### ISSUE TITLE
1.0.13 labeled as the "latest release" under releases

### ISSUE THREAD

**Issue by heewookl** [statgen/bamUtil#43]
Hi, first of all, thanks for making and maintaining bamUtil and it has been very helpful for my research.

For some reason, on the releases page, 1.0.13 is still labeled as the "Latest release", although 1.0.14 is available and this seems confusing for some people. Could you please update the latest release label to 1.0.14? Thank you!

**Comment by jonathonl** [comment]
Fixed.
