### ISSUE TITLE
Building bamUtil returns error: call of overloaded 'to_string(int&)' is ambiguous

### ISSUE THREAD

**Issue by sam0per** [statgen/bamUtil#49]
Hi there,
I am encountering an error while building this repository using the following codes:

`git clone git://github.com/statgen/bamUtil.git`
`cd bamUtil`
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib`
`module load gcc/v6.3.0`
`make cloneLib`
`make`    ## here comes the error
...
VcfRecord.cpp: In member function 'bool VcfRecord::read(InputFile*, bool, VcfRecordDiscardRules&, VcfSubsetSamples*)':
*VcfRecord.cpp:160: error: call of overloaded 'to_string(int&)' is ambiguous*
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2604: note: candidates are: std::string std::to_string(long long int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2610: note:                 std::string std::to_string(long long unsigned int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2616: note:                 std::string std::to_string(long double)
VcfRecord.cpp: In member function 'bool VcfRecord::write(InputFile*, bool)':
VcfRecord.cpp:199: error: call of overloaded 'to_string(int&)' is ambiguous
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2604: note: candidates are: std::string std::to_string(long long int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2610: note:                 std::string std::to_string(long long unsigned int)
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/basic_string.h:2616: note:                 std::string std::to_string(long double)
make[3]: *** [obj/VcfRecord.o] Error 1
make[2]: *** [vcf] Error 2
make[1]: *** [../../libStatGen/libStatGen.a] Error 2
make[1]: Leaving directory `/proj/data9/samuel/modules/bamUtil/src'
make: *** [src] Error 2

I am working on a HPC cluster that uses linux
Any suggestion to avoid the ambiguities?

**Comment by mktrost** [comment]
Could you try updating libStatGen/vcf/VcfRecord.cpp:

line 160
from
std::to_string(my1BasedPosNum) + " (chr:pos) - " + e.what();
to
std::to_string(static_cast<long long>my1BasedPosNum) + " (chr:pos) - " + e.
what();

line 199
from:
std::string strPos = std::to_string(my1BasedPosNum);
to:
std::string strPos = std::to_string(static_cast<long long>my1BasedPosNum);

Let me know if that resolves your issue or if you encounter additional
issues.

**Comment by sam0per** [comment]
Thanks for your quick suggestion and it seems to work if you enclose my1BasePosNum in brackets too.

std::to_string(static_cast<long long>(my1BasedPosNum)) + " (chr:pos) - " + e.what();
std::string strPos = std::to_string(static_cast<long long>(my1BasedPosNum));

Unfortunately, there is another error that pops up and perhaps it is related to the zlib package which I am not able to load on the current HPC cluster. I am in contact with the admin and I will update you if you do not have any further comments at the moment. Here is the error:

../../libStatGen/libStatGen.a(GzipFileType.o): In function `GzipFileType::GzipFileType(char const*, char const*)':
GzipFileType.cpp:(.text+0xdf): undefined reference to `gzopen64'
../../libStatGen/libStatGen.a(GzipFileType.o): In function `GzipFileType::seek(long, int)':
GzipFileType.cpp:(.text._ZN12GzipFileType4seekEli[_ZN12GzipFileType4seekEli]+0x9): undefined reference to `gzseek64'
../../libStatGen/libStatGen.a(GzipFileType.o): In function `GzipFileType::tell()':
GzipFileType.cpp:(.text._ZN12GzipFileType4tellEv[_ZN12GzipFileType4tellEv]+0x5): undefined reference to `gztell64'
collect2: error: ld returned 1 exit status
make[1]: *** [../bin/bam] Error 1

**Comment by sam0per** [comment]
OK, problem solved using (this)[https://github.com/statgen/libStatGen/issues/12] suggestion

**Comment by sam0per** [comment]
OK, problem soves following [this suggestion](https://github.com/statgen/libStatGen/issues/12)
