### ISSUE TITLE
 the clang compiler does not support -pg option on versions of OS X 10.9 and later 

### ISSUE THREAD

**Issue by OscarChou211** [statgen/bamUtil#60]
Hi there, 

I was trying to install bamUtil. 

However, it shows the following error: 

clang: error: the clang compiler does not support -pg option on versions of OS X 10.9 and later
make[1]: *** [../bin/profile/bam] Error 1
make: *** [src] Error 2 

I wonder what should I do? 

Thank you!

**Comment by jonathonl** [comment]
Presumably, you don't need a profile build. Run `make` instead of `make all`.

**Comment by OscarChou211** [comment]
Sorry, sorry for not making it clear. 

I ran "make" and it went okay. Then I ran  make install INSTALLDIR=/Users/apple/bamUtil-master 

But the above error appeared. 

Sorry I am a newbie to bioinformatics and coding and may need some guidances..

Thank you!

**Comment by jonathonl** [comment]
I see... I'm guessing the 'install' target is dependent on the 'all' target. You should be able to get away with simply running `make && cp bin/bam /Users/apple/bamUtil-master/bin/`.

**Comment by OscarChou211** [comment]
Thank you very much for helping! It is working now without any problem! Thank you!
