### ISSUE TITLE
build is broken due to deprecated git protocol

### ISSUE THREAD

**Issue by ahvigil** [statgen/bamUtil#67]
Running `make cloneLib` is broken with the following error:
```
Cloning into 'libStatGen'...
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```
According to the [linked blog post](https://github.blog/2021-09-01-improving-git-protocol-security-github/#when-are-these-changes-effective):
> unencrypted git:// offers no integrity or authentication, making it subject to tampering. We expect very few people are still using this protocol, especially given that you can’t push (it’s read-only on GitHub). We’ll be disabling support for this protocol.

Also in the same blog post:
> January 11, 2022 | Final brownout.This is the full brownout period where we’ll temporarily stop accepting the deprecated key and signature types, ciphers, and MACs, and the unencrypted Git protocol. This will help clients discover any lingering use of older keys or old URLs.

Which explains why we're seeing the error now.

**Comment by hyunminkang** [comment]
Thanks for raising this issue, and also for the pull request
